name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    uses: jill64/workflows/.github/workflows/publish-pages.yml@main
    with:
      build-command: export PUBLIC_SENTRY_DSN=${{ vars.PUBLIC_SENTRY_DSN }} && npm run build
