name: Integration

on:
  pull_request:
    branches: main

jobs:
  integration:
    uses: jill64/workflows/.github/workflows/run-playwright.yml@main
    with:
      test-command: export PUBLIC_SENTRY_DSN=${{ vars.PUBLIC_SENTRY_DSN }} && npm run test:e2e
